### ISSUE TITLE
lsp-ui-sideline only show the first line of error.

### ISSUE THREAD

**Issue by nasyxx** [emacs-lsp/lsp-ui#150]
I am not sure if it is a bug of the sideline or my wrong config.

The error shows in normal:

<img width="455" alt="screen shot 2018-06-21 at 7 47 47 pm" src="https://user-images.githubusercontent.com/5007613/41717769-6662b6a2-758d-11e8-8f9e-fa64c4141a0c.png">

The error shows in sideline:
<img width="650" alt="screen shot 2018-06-21 at 7 48 15 pm" src="https://user-images.githubusercontent.com/5007613/41717774-69e72826-758d-11e8-99ac-312032f5d000.png">

**Comment by whirm** [comment]
I'm hitting the same issue with `ocaml-langague-server`.

**Comment by thirdeyefunction** [comment]
@coreyconnor I tried your changes with ocaml-language-server and while it's an improvement, the alignment is kind of wonky: ![Imgur Image](https://i.imgur.com/I8GYBY0.png)

**Comment by coreyoconnor** [comment]
@thirdeyefunction I think there are two issues there: The first error message line has extra spaces at the end; the use of right justification for the block is questionable.

The first issue should be easy: always trim spaces from each line. I think that's universally applicable.

As for the second, the right justification, not sure if there is a universal treatment. I'm fine with the right justification. In this case tho, with the line being so short and the added spaces, it really stands out.

**Comment by coreyoconnor** [comment]
This is complete. All recent changes are only rebases. Please merge.

**Comment by aqxa1** [comment]
I just want to note that this issue is back as of 401e69bffc9d581fb979389fdf6de47c3f4084dd, since `lsp-ui-sideline-diagnostic-max-lines` is now set to `1`. Fair enough if the old default causes issues, but if anyone is wondering why it's broken again, that's why. Easy to fix on the config side, thankfully:
`(setq lsp-ui-sideline-diagnostic-max-lines 3)`
or set through the customize interface.
