### ISSUE TITLE
lsp-ui sideline is displaying symbol info in wrong order

### ISSUE THREAD

**Issue by yyoncho** [emacs-lsp/lsp-ui#171]
There are servers which handle the requests asynchronously and they might return the symbol info, not in the order they have been called (e. g. JDT LS). The result is that `lsp-ui` displays the symbol information in the wrong order.

**Comment by brotzeit** [comment]
Is this still an issue ?

**Comment by yyoncho** [comment]
![wrong-order](https://user-images.githubusercontent.com/13259670/76147058-52994900-60a1-11ea-82b2-d459dc23bc1a.png)


Yes. In this case, obtaining `String` data is slowest and is always the last symbol in the list.

**Comment by yyoncho** [comment]
Just want to mention that using emacs-promise/emacs-deferred will be very helpful for such issues: https://github.com/emacs-lsp/lsp-mode/issues/1471

**Comment by kurnevsky** [comment]
If I got it right it can't be shown with strict ordering. We don't know the line length that we will receive from the server and this length affects the line number where it can be displayed.

**Comment by yyoncho** [comment]
> If I got it right it can't be shown with strict ordering. We don't know the line length that we will receive from the server and this length affects the line number where it can be displayed.

Why? We do async calls and we can render the elements in the same order as they are in the current line.

**Comment by kurnevsky** [comment]
Because if we got a too wide response which can't be displayed on the next line (because it won't fit) it will find a line with narrower text where it can be displayed. So before we received a response we can't know the exact line where it'll be shown and the only way to make all lines in order is to shift previously displayed lines.

**Comment by yyoncho** [comment]
Hm, are you saying the wrong order is caused by the length of the item, not on the order of receiving the response?

**Comment by kurnevsky** [comment]
It's async calls that make these lines out of order. Regarding different line lengths - not sure what happens. I'd assume that we just skip those lines where the response can't fit and leave them empty, but need to check/test it. But my point is that we can't simply make them in order just because we can't know in advance which lines we should skip.

**Comment by yyoncho** [comment]
Can we make sure that we render the symbols once we get them all and start rendering/placing from the first one and make sure that the symbols after the first symbol are placed bellow it? It may even reduce blinking/noise.

**Comment by yyoncho** [comment]
Apart from that, we should not refresh the symbols when the user moves the cursor on the same line.

**Comment by kurnevsky** [comment]
> Can we make sure that we render the symbols once we get them all and start rendering/placing from the first one and make sure that the symbols after the first symbol are placed bellow it?

We can, but as for me I'm not sure I'd prefer this behavior just to have ordered results. I encountered cases when one requests take seconds to complete while other we receive almost immediately (in metals). I kind of like that we display the result as fast as possible.

**Comment by yyoncho** [comment]
Fair enough.

**Comment by kurnevsky** [comment]
But we always can make thinks defined by user settings :)

> Apart from that, we should not refresh the symbols when the user moves the cursor on the same line.

It's defined by `lsp-ui-sideline-update-mode` setting. Recently it was changed to refresh symbols even when the cursor stays on the same line, not sure why.

**Comment by yyoncho** [comment]
> It's defined by `lsp-ui-sideline-update-mode` setting. Recently it was changed to refresh symbols even when the cursor stays on the same line, not sure why.

The code actions depend on the cursor position.

**Comment by sebastiencs** [comment]
The ordering has been fixed with https://github.com/emacs-lsp/lsp-ui/pull/490
Note that the order will not be respected if there is not enough space on the line:
- If item number 3 is too big for line number 3, it will be display on line number 4
- Item number 4 will be display on line number 3

> We can, but as for me I'm not sure I'd prefer this behavior just to have ordered results. I encountered cases when one requests take seconds to complete while other we receive almost immediately (in metals). I kind of like that we display the result as fast as possible.

@kurnevsky I didn't consider this case of slow request. Since that PR it wait for all requests to have completed to display them all.
Please open another issue if you want a variable to control this behavior

**Comment by kurnevsky** [comment]
Yes, I'd definitely prefer old behavior since with metals I get info for each symbol with different delays, and for some of them these delays can be few seconds. I think I'll make a PR for that.
