### ISSUE TITLE
lsp-ui-peek-find-workspace-symbol error

### ISSUE THREAD

**Issue by r-darwish** [emacs-lsp/lsp-ui#217]
I tried using the above function in two Rust projects. What I get is:

`insert-file-contents-literally: Read error: Is a directory, /home/roeyd/src/alma/src`

`lsp-ui-find-workspace-symbol` works as expected.

[Here](https://github.com/drrlvn/.emacs.d) is my configuration.

**Comment by ret2libc** [comment]
Same error here. Did you find a solution @r-darwish ?

**Comment by r-darwish** [comment]
Nope. The error still occurs

**Comment by ret2libc** [comment]
@MaskRay are you aware of any problem around this? I'm using ccls + lsp-ui in emacs. Is there anything I can do to help debug the issue? Finding symbols in a workspace is really useful and I would really like to see this fixed.

**Comment by yyoncho** [comment]
proposed fix #406

**Comment by MaskRay** [comment]
@r-darwish Do you know why `insert-file-contents-literally` may run on a directory?

@ret2libc I mainly use `lsp-ui-find-workspace-symbol` instead of `lsp-ui-peek-find-workspace-symbol`, because `workspace/symbol` results can be very long. `lsp-ui-peek` may be a bit clumsy when there are numerous results.
