### ISSUE TITLE
How to configure linting for typescript?

### ISSUE THREAD

**Issue by zer09** [emacs-lsp/lsp-ui#279]
I have a tslint.json on my project, but I think lsp-ui doesn't use it.

I cant find any on the readme to configure the linting, how should I do it?

Thanks

**Comment by DBoroujerdi** [comment]
I don't think you can. Looking at the typescript-language-server github it makes no mention of linting, and neither does the codebase. Which makes sense, since vscode doesn't provide typescript linting out of the box either.

What we need is a way of disabling lsp-ui-flycheck entirely as flycheck + its built in typescript checker works fine. Unfortunately lsp-ui overrides that. 

I'll post back here if I figure it out!

**Comment by DBoroujerdi** [comment]
Got it. 

`(flycheck-add-next-checker 'lsp-ui 'typescript-tslint)`

This seems chains the `typescript-tslint` checker onto the `lsp-ui' checker so that it runs after in the same buffer.

Here I have flycheck using the built in `typescript-tslint` checker and lsp-ui doing its function description thing.

<img width="497" alt="Screenshot 2019-08-10 at 23 16 39" src="https://user-images.githubusercontent.com/274674/62827344-3db90d80-bbc5-11e9-8327-a87cb4c6bf6d.png">

**Comment by yyoncho** [comment]
Closing based on https://github.com/emacs-lsp/lsp-ui/issues/279#issuecomment-520183688
