### ISSUE TITLE
Package maintainers

### ISSUE THREAD

**Issue by brotzeit** [emacs-lsp/lsp-ui#332]
We obviously need active maintainers for this package. Volunteers ? I will try to help.

**Comment by sebastiencs** [comment]
Hi @brotzeit 

I've been quite busy the last few months and didn't find time to maintain lsp-ui.
I have more time now and plan to commit more on lsp-ui.

I just submitted [some changes](https://lists.gnu.org/archive/html/emacs-devel/2019-11/msg00203.html) to emacs in order to fix all (hopefully 🤞) the problems with lsp-ui-sideline.
More changes will follow on emacs to improve lsp-ui.

With that being said, new maintainers are welcome !

cc @yyoncho @MaskRay

**Comment by MaskRay** [comment]
Nice! I see that @brotzeit has already been added to the lsp-ui team.

**Comment by brotzeit** [comment]
lsp-ui seems to have a large user base. It would be a shame if the package stays unmaintained. @sebastiencs great to hear that you will have time again. I will try to contribute, but I will need some time to get familiar with the code base.

**Comment by danielmartin** [comment]
Let me know if I can help.

**Comment by brotzeit** [comment]
@danielmartin That would be great.

**Comment by brotzeit** [comment]
@yyoncho @sebastiencs @MaskRay Can somebody please give @danielmartin write access.

**Comment by yyoncho** [comment]
> @yyoncho @sebastiencs @MaskRay Can somebody please give @danielmartin write access.

Done

**Comment by jcs090218** [comment]
Are you guys still looking for more maintainers? I'm interested to co-maintain this package. 

Let me know if I can help! Thanks!

**Comment by brotzeit** [comment]
Sure. @yyoncho please invite @jcs090218.

**Comment by jcs090218** [comment]
Is there anything that may hamper this? 😖 Thanks! 😄

**Comment by yyoncho** [comment]
> Sure. @yyoncho please invite @jcs090218.

Done. I think that you have the right to do that too.

**Comment by yyoncho** [comment]
@jcs090218 

> Is there anything that may hamper this?  Thanks!

This seems to be the most wanted and the most requested enhancement - https://github.com/emacs-lsp/lsp-ui/issues/296 .

Also in you are interested in language-specific work you may share the language servers that you use. This is usually the most interesting work since it will directly affect your daily coding activities. And finally, if you want to implement a certain feature/bug don't hesitate to ask here or in gitter chat.

**Comment by jcs090218** [comment]
> This seems to be the most wanted and the most requested enhancement - #296 .

Let me investigate this feature! I am currently cleaning up lsp projects; meanwhile I am also reading the code base implementation simultaneously while I am doing that. Sorry that I regularly fix code and worry readability before I implement next new feature.

> Also in you are interested in language-specific work you may share the language servers that you use. This is usually the most interesting work since it will directly affect your daily coding activities. And finally, if you want to implement a certain feature/bug don't hesitate to ask here or in gitter chat.

No problem! I code a lot of languages TBH. I usually change my daily programming language base on different circumstances. The recent programming languages I have used are `javascript`, `typescript` and `csharp`. But I don't often bother `lsp-mode` if it doesn't get things right. Unless it really poorly executed. 😖 

@yyoncho Anyway, Would you mine if I joined the organization? I might want co-maintain multiple `lsp` packages, and I think is easier for you manage me as a team using GitHub organization's feature.

These are packages I am interested in.

#### Interested but probably less activity because there are multiple very active maintainers (I assumed)

- [ ] `lsp-mode` - of course
- [ ] `dap-mode`
- [ ] `lsp-java` - I love java but I haven't code in java for a while.

#### Interested and I am more likely to be active.

- [ ] `lsp-ui` - This is probably the most important package for me now.
- [ ] `lsp-ivy` - Yes, I use ivy. :P

#### Other packages that I have experience with and able to help

- [ ] `helm-lsp` - I am able to help.
- [ ] `lsp-focus`
- [ ] `lsp-origami`

Let me know what you think! :)

**Comment by yyoncho** [comment]
I added you to the organization. Please, before starting to work on a reported issue, assign it to you or drop a note to avoid collisions.

> Interested but probably less activity because there are multiple very active maintainers

Still, there are a lot of open tasks there.

**Comment by jcs090218** [comment]
> I added you to the organization. Please, before starting to work on a reported issue, assign it to you or drop a note to avoid collisions.

Thanks! I appreciated! Will do!

> Still, there are a lot of open tasks there.

Got you! If any package needs help, let me know!

**Comment by yyoncho** [comment]
> Got you! If any package needs help, let me know!

It is not up to me - if you like a task and you have free time go ahead and start working on it. I can only advise what in my opinion is with the highest priority.

**Comment by anonimitoraf** [comment]
Hey, interested in helping out too

**Comment by brotzeit** [comment]
@anonimitoraf do you know how to write elisp ? Usually we add contributors to the project when they've added a few commits. You can always open pull requests when you want to add some code. Get familiar with the lsp-ui codebase and the issue tracker. Unfortunately we currently don't have an active maintainer that knows enough about the code base to review larger pull requests properly. I'm always hesitant to merge pull requests since we often had the situation that we fixed one bug and created a new one.  Writing tests for lsp-ui is also very difficult(often simply not possible) and currently we have no idea if our code is actually working.

**Comment by anonimitoraf** [comment]
I've started learning

> Usually we add contributors to the project when they've added a few commits. You can always open pull requests when you want to add some code

Right, Makes sense

> Writing tests for lsp-ui is also very difficult(often simply not possible)

Why is this the case?

**Comment by brotzeit** [comment]
For example you can't make additional frames when running tests for emacs.
