### ISSUE TITLE
documentation frame wrong size

### ISSUE THREAD

**Issue by dsvensson** [emacs-lsp/lsp-ui#334]
Using Golang, but apparently this is the same in other languages. Most often have to jump to an empty line before jumping to a position where I want to show the documentation - otherwise the size of the frame will be too narrow, or too short to show all of the documentation.

Sometimes it's correct width though, and sometimes it's as tall (really tall) as the documentation, and sometimes it's reasonably tall and i can scroll with my wheel to read the long docs, which is fine.

From asking at the official chat, it seems that I'm not the only one with this issue.

Sometimes when the frame has been drawn correctly for a doc string, and when a next shorter doc string is shown, it's like the frame just moves right, so the text is placed correctly, but the frame is just transposed to the new (x,y) upper left corner without changing the size, and thus the right border line of the frame is hidden outside of the right end of the buffer.

**Comment by jtl5770** [comment]
Well I can at least testify for java that it is the same there - it's a game of switching around lines back and forth, to a empty line or another symbol, until at last the width is correct.

**Comment by chrbirks** [comment]
In case you haven't realized it, it seems like the box width is calculated after the box has been drawn. So the box width used is the one calculated for the last cursor position. The top-right anchor point is always correctly calculated though.

And the problem is present for all values of `lsp-ui-doc-alignment`.

**Comment by Sorixelle** [comment]
Can confirm this is still an issue, exactly as chrbirks described it. On the first hover, the frame is the wrong size, and uses the correct size of the previously hovered term, but on the second, it's correct. Did some basic debugging with my basic elisp knowledge (read: `debug-on-entry` on `set-frame-size`) and saw that the width and height appear to be being set correctly in `lsp-ui-doc--move-frame`, so I'm not quite sure what the issue is.

Example of the behaviour:
![lsp-ui-doc gif](https://i.imgur.com/g8LwMOa.gif)

**Comment by abbaswasim** [comment]
@Sorixelle Is this suppose to be fixed with https://github.com/emacs-lsp/lsp-ui/pull/459? I still see similar issues.
<img width="1848" alt="Screenshot 2024-01-03 at 17 32 58" src="https://github.com/emacs-lsp/lsp-ui/assets/5260991/005c81a8-3478-4c72-9bb6-a49ef582a663">

```
GNU Emacs 29.1 (build 1, x86_64-apple-darwin21.6.0, Carbon Version 165 AppKit 2113.6) of 2023-08-08
```
