### ISSUE TITLE
lsp-ui-doc child frame should move or disappear when Emacs scrolls

### ISSUE THREAD

**Issue by tsuu32** [emacs-lsp/lsp-ui#428]
When `lsp-ui-doc-position` is `'at-point`, doc child frame is shown near the cursor.
If I scroll the buffer by mouse wheel (or `C-l`, `C-u 5 C-v`), then the doc child frame stays in the same position.

I think the doc child frame should move to proper position or disappear when Emacs scrolls.

**Comment by andreyorst** [comment]
In VSCode it is possible to keep documentation popup near cursor while scrolling, because cursor can go offscreen with the documentation. Since Emacs can't allow cursor to go offscreen, and it will move with the upper or lower bound of the frame, I think child frame should disappear when window is scrolled.

**Comment by sebastiencs** [comment]
That's done in https://github.com/emacs-lsp/lsp-ui/commit/6f64b85e4df3e1346aca5a3e7acfd6ad3d9d32e3.
The doc will move while scrolling

**Comment by tsuu32** [comment]
Thanks for the inplementation!!
This feature is very useful for me.

**Comment by sebastiencs** [comment]
@tsuu32 You're welcome
