### ISSUE TITLE
eldoc has no syntax highlighting

### ISSUE THREAD

**Issue by aaronjensen** [emacs-lsp/lsp-ui#436]
I don't know if this is a problem in my config, or what, but I've noticed that lsp's eldoc with TypeScript has no syntax highlighting:

<img width="583" alt="CleanShot 2020-04-21 at 05 38 39@2x" src="https://user-images.githubusercontent.com/8588/79866924-5ef80d80-8392-11ea-8199-3b15884f4853.png">

I have two emacs configs—my spacemacs config highlights this properly, but my own Emacs config does not. Is there a variable I'm missing somewhere?

Thanks!

**Comment by yyoncho** [comment]
I guess installing one of these will fix your issue. 

>  (rjsx-mode . "javascript")
>  (js2-mode . "javascript")
>  (js-mode . "javascript")

**Comment by aaronjensen** [comment]
Thank you for the quick reply. Unfortunately, installing the first doesn't help and the other two are installed by default.

Is there a TypeScript specific thing that must be installed to highlight the hover/eldoc?

**Comment by Sleepful** [comment]
I also get no syntax highlighting. `Tide` does it fine. The issue is there with any mode that does syntax highlighting in the main buffer, the mini buffer simply isn't being highlighted.
I have tried them all: `js2-mode js-mode js-jsx-mode rjsx-mode web-mode`

**Comment by waymondo** [comment]
I'm also experiencing this. I haven't absorbed the source code fully, but in my case it happens when then second condition in `lsp-ui-doc--extract` is hit:

https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L329

This eventually calls `lsp-ui-doc--extract-marked-string` but never ends up using the extracted language when rendering the ui doc in the childframe.

If I change the last line of that method (https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L305) to use `(lsp--render-string)` along with providing the language, I get the syntax highlighting I'd expect. Here's the altered function:

```
(defun lsp-ui-doc--extract-marked-string (marked-string &optional language)
  "Render the MARKED-STRING with LANGUAGE."
  (string-trim-right
   (let* ((string (if (stringp marked-string)
                      marked-string
                    (lsp:markup-content-value marked-string)))
          (with-lang (lsp-marked-string? marked-string))
          (language (or (and with-lang
                             (or (lsp:marked-string-language marked-string)
                                 (lsp:markup-content-kind marked-string)))
                        language))
          (markdown-hr-display-char nil))
     (cond
      (lsp-ui-doc-use-webkit
       (if (and language (not (string= "text" language)))
           (format "```%s\n%s\n```" language string)
         string))
      (t (lsp--render-string (lsp-ui-doc--inline-formatted-string string) language))))))
```

Not sure if there are any unintended consequences, but if this seems like the correct fix, I can provide a PR.

**Comment by jcs090218** [comment]
@waymondo I think you have the correct fix! Can you open a PR for this? Thanks! :)

**Comment by waymondo** [comment]
sure thing
