### ISSUE TITLE
child frame being drawn too wide

### ISSUE THREAD

**Issue by covercash2** [emacs-lsp/lsp-ui#449]
# Description
this may be a Rust specific issue. i want to customize the width of the child frame.

the canonical way:
```
; set width of child frame to 80 chars
(setq lsp-ui-doc-max-width 80)
```
this does restrict the text, mostly, to 80 columns, but there is a row of `-`s that appears on anything that's properly documented. when i try to copy the text in the child frame buffer i get:
```
sheepish::directory
___

pub struct Directory

Directory state data for building widgets.
```
but the child frame is actually wider than its parent because of all the `-`.

then i had the idea to:
```
(add-to-list 'lsp-ui-doc-frame-parameters '(width 0.3))
```
which didn't change much. now i'm at:

```
(add-hook 'lsp-ui-doc-frame-hook
	    (lambda (frame window)
              (set-frame-parameter frame 'width 0.3)))
```

i saw there was another issue with Go doing something similar, but that issue was closed.

my elisp isn't great. any help appreciated

**Comment by CSRaghunandan** [comment]
+1

This definitely needs to be documented better. I was so confused when I set `lsp-ui-doc-max-width` to `100` only for it to not change the way the doc frames were being rendered.

**Comment by bryandmc** [comment]
YES this is happening to me right now. It's a new-ish change from somewhere that is causing it. I think it might be rust-specific.. Because it doesn't happen in python, nor java.. Please someone help!! I can't seem to make them smaller with any of my elisp tricks. 

It will absolutely happen to anyone using the newest lsp/lsp-ui + rust-mode + rust-analyzer as the rust lsp backend. Then it will make child windows take up the entire screen. 

![image](https://user-images.githubusercontent.com/774915/83586130-8cdb8080-a500-11ea-8a9e-acd257da8286.png)

I drew a red line where the text-edge actually is. Just to be clear. Anyone know how to fix this?

**Comment by yyoncho** [comment]
@bryandmc can you retry with page-break-lines-mode turned off?

**Comment by alanz** [comment]
I think #442 is the same issue.

**Comment by bryandmc** [comment]
@yyoncho Doesn't seem to affect it.. Happens with the mode on or off.. 

It has to be something to do with the markdown rendering. Is there a variable to control the actual width of the child window? Instead of just controlling the text inside it (which before, had the same affect).

**Comment by alanz** [comment]
My theory is that the markdown renderer is asked to render it, then the window is sized by the longest line in the rendered markdown.  But by definition a horizontal rule fills all the available space.

But I am not all that familiar with the code, so I had trouble identifying where exactly this happens.

A hack would be to strip out anything that uses "full width" when doing the markdown render for max width determination.  Or to ignore those lines when checking for max width.

**Comment by covercash2** [comment]
yeah, i guess i didn't search the issues well enough.

it makes sense that it's a markdown issue with `<br>`.

i'll go ahead and close this as a duplicate of #[442](https://github.com/emacs-lsp/lsp-ui/issues/442)
