### ISSUE TITLE
Defaults lsp-ui-peek-expand-function to unfold all xref items

### ISSUE THREAD

**Issue by MaskRay** [emacs-lsp/lsp-ui#46]
It currently displays xref items in the current buffer and folds others. I use `(setq lsp-ui-peek-expand-function (lambda (xs) (mapcar #'car xs)))` to unfold all files. I wonder if this is a better default to unfold all xref items.

C/C++ has separated header files and `.c/.cc/.cpp/.cxx/...`. Finding references in C/C++ `a.h` will likely reveal references in `a.cc`.

**Comment by sebastiencs** [comment]
I really think it's a bad idea.
The issue is, in case there are a lot of files, it would be necessary to open them all, which can take a lot of time and unnecessary ressources.
vscode doesn't unfold items in its peek view too.

You can change that behavior with `lsp-ui-peek-expand-function` but I think the default should be keep as it is now.

**Comment by MaskRay** [comment]
Then provide `(lambda (xs) (mapcar #'car xs))` as an alternative expand-function?

**Comment by sebastiencs** [comment]
The variable `lsp-ui-peek-expand-function` has been created specifically for this purpose: https://github.com/emacs-lsp/lsp-ui/issues/8.
The user is free to choose whatever behavior he wants
