### ISSUE TITLE
lsp-ui-doc popup for function documentation doesn't show up for elixir-ls but works for other language servers

### ISSUE THREAD

**Issue by x-ji** [emacs-lsp/lsp-ui#478]
- OS: MacOS 10.15.6
- Emacs: GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.7.0, Carbon Version 158 AppKit 1671.6) of 2020-06-14
- lsp-mode: lsp-mode-20200728.1517
- lsp-ui: lsp-ui-20200718.1035

I am at a loss at the behavior that I'm seeing with my Emacs (Spacemacs). I have `lsp-ui-doc-mode` enabled and the popup shows up correctly upon hovering for language servers such as `vls` (Vue.js). However, with `elixir-ls`, nothing shows up.

I set `lsp-log-io` to `t` and looked at the logs. I saw that `textDocument/hover` seems to have been correctly triggered and a response is received, e.g. 

```
[Trace - 09:35:52 PM] Sending request 'textDocument/hover - (190)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jx/test/backend/test/support/data_case.ex"
  },
  "position": {
    "line": 64,
    "character": 5
  }
}


[Trace - 09:35:52 PM] Received response 'textDocument/hover - (190)' in 31ms.
Result: {
  "range": {
    "start": {
      "line": 64,
      "character": 2
    },
    "end": {
      "line": 64,
      "character": 5
    }
  },
  "contents": "> Kernel.def(call, expr \\\\\\\\ [])\n\nDefines a public function with the given name and body.\n\n## Examples\n\n    defmodule Foo do\n      def bar, do: :baz\n    end\n\n    Foo.bar()\n    #=> :baz\n\nA function that expects arguments can be defined as follows:\n\n    defmodule Foo do\n      def sum(a, b) do\n        a + b\n      end\n    end\n\nIn the example above, a `sum/2` function is defined; this function receives\ntwo arguments and returns their sum.\n\n## Default arguments\n\n`\\\\` is used to specify a default value for a parameter of a function. For\nexample:\n\n    defmodule MyMath do\n      def multiply_by(number, factor \\\\ 2) do\n        number * factor\n      end\n    end\n\n    MyMath.multiply_by(4, 3)\n    #=> 12\n\n    MyMath.multiply_by(4)\n    #=> 8\n\nThe compiler translates this into multiple functions with different arities,\nhere `MyMath.multiply_by/1` and `MyMath.multiply_by/2`, that represent cases when\narguments for parameters with default values are passed or not passed.\n\nWhen defining a function with default arguments as well as multiple\nexplicitly declared clauses, you must write a function head that declares the\ndefaults. For example:\n\n    defmodule MyString do\n      def join(string1, string2 \\\\ nil, separator \\\\ \" \")\n\n      def join(string1, nil, _separator) do\n        string1\n      end\n\n      def join(string1, string2, separator) do\n        string1 <> separator <> string2\n      end\n    end\n\nNote that `\\\\` can't be used with anonymous functions because they\ncan only have a sole arity.\n\n## Function and variable names\n\nFunction and variable names have the following syntax:\nA _lowercase ASCII letter_ or an _underscore_, followed by any number of\n_lowercase or uppercase ASCII letters_, _numbers_, or _underscores_.\nOptionally they can end in either an _exclamation mark_ or a _question mark_.\n\nFor variables, any identifier starting with an underscore should indicate an\nunused variable. For example:\n\n    def foo(bar) do\n      []\n    end\n    #=> warning: variable bar is unused\n\n    def foo(_bar) do\n      []\n    end\n    #=> no warning\n\n    def foo(_bar) do\n      _bar\n    end\n    #=> warning: the underscored variable \"_bar\" is used after being set\n\n## `rescue`/`catch`/`after`/`else`\n\nFunction bodies support `rescue`, `catch`, `after`, and `else` as `Kernel.SpecialForms.try/1`\ndoes. For example, the following two functions are equivalent:\n\n    def format(value) do\n      try do\n        format!(value)\n      catch\n        :exit, reason -> {:error, reason}\n      end\n    end\n\n    def format(value) do\n      format!(value)\n    catch\n      :exit, reason -> {:error, reason}\n    end\n\n\n"
}
```

However, nothing pops up on my UI whatsoever.

If I try to run `lsp-describe-thing-at-point`, I also correctly see the documentation displayed in a separate buffer.

The response I received from `vls` in comparison:

```
[Trace - 09:32:13 PM] Sending request 'textDocument/documentLink - (188)'.
Params: {
  "textDocument": {
    "uri": "file:///Users/jx/test/lib/templates/src/App.vue"
  }
}


[Trace - 09:32:13 PM] Received response 'textDocument/hover - (186)' in 42ms.
Result: {
  "range": {
    "end": {
      "character": 13,
      "line": 13
    },
    "start": {
      "character": 5,
      "line": 13
    }
  },
  "contents": [
    "The template element is used to declare fragments of HTML that can be cloned and inserted in the document by script\\."
  ]
}

```

I don't see the difference between these two responses that could potentially cause the popup to fail to show up in the first case.

Could there be some language-specific configuration for `lsp-ui-doc` that caused this? I tried to look for it and couldn't find anything to that effect, and it seems that the configuration should be global. This situation really confuses me.

**Comment by x-ji** [comment]
The only thing I could think of is that the contents returned by `elixir-ls` is considerably longer than the contents returned by `vls` in this case. Could there be some configuration which prevented the popup from showing up when the contents are too long?

**Comment by J3RN** [comment]
I'm having the same issue, and have done some debugging. Ultimately, the value of the `content` variable inside [`lsp-ui-doc--callback`](https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L710) is `string`, but [`lsp-ui-doc--extract`](https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L286) expects a `MarkedString`, `MarkedString[]`, or `MarkupContent`. The `cond` has no matches, and the return value is `nil`.

My bigger question now is whether this type mismatch is actually the failure of lsp-ui or of the Elixir language server.

**Comment by x-ji** [comment]
@J3RN Interesting. Would it make sense for you to comment in the issue https://github.com/elixir-lsp/elixir-ls/issues/320 I opened in the elixir-ls repo, so that the maintainer there could confirm whether this is related to the problem?

**Comment by x-ji** [comment]
I actually sometimes see the function doc displayed in a temporary buffer at the bottom of the screen. That might be something separate from `lsp-ui` though.

**Comment by J3RN** [comment]
I did a deep dive on this topic. Here's what I learned:
- The Elixir LS _is_ returning a valid response. `MarkedString` is a actually a union type of `string` and an object that looks like `{ language: string; value: string }`. [The documentation for `MarkedString`](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover) (you'll have to scroll down a little). Since the Elixir LS returns a `string`, it complies with this type and is valid.
- [`lsp-mode` defines `MarkedString` as an interface](https://github.com/emacs-lsp/lsp-mode/blob/master/lsp-protocol.el#L470) (it's not; it's a type) of an object containing `language` and `value` keys, which only matches one half of the union type from the Language Server Protocol specification.

  However, `lsp-mode` does not (yet) have the ability to define types, union or otherwise. Some other types from the LSP spec are also defined as interfaces in `lsp-mode` to varying degrees of success.
- `MarkedString` is **deprecated** in favor of the [`MarkupContent` interface](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#markupContent), as you may have noticed from the spec linked above. In fact, it was deprecated _three years ago_ but is still technically a valid part of the specification&mdash;just one that's going away soon™.

I believe the Right Answer™ here would be to add support for union types to `lsp-mode`. They are technically a valid part of the LSP spec and probably aren't going anywhere soon.

The Easy Answer would be to add a work-around for this use-case, which will solve this specific issue.

On the other hand, Elixir LS should migrate its hover responses from `string`s to valid `MarkupContent`. I'll start work on that when I have some time.

**Comment by J3RN** [comment]
Hey @x-ji! My PR to the Elixir Language Server was merged, so the documentation-on-hover functionality should now work after you re-compile and re-release your local ElixirLS. 
![image](https://user-images.githubusercontent.com/2058614/90262758-b2e4a180-de1c-11ea-93b2-c2add464d733.png)

I'll leave it to your discretion as to whether you want to close this issue, or wait for #485 (approved, but not merged) to be merged for `lsp-ui` compatibility with older ElixirLS instances.

**Comment by x-ji** [comment]
Wow. That's impressively fast. Now I have the popup doc in Emacs 😄 Thanks a lot!
