### ISSUE TITLE
Strange icon in lsp-ui-sideline when showing code actions.

### ISSUE THREAD

**Issue by clearmisp** [emacs-lsp/lsp-ui#74]
lsp-ui-sideline displays a strange icon when showing code action information. More correctly, lsp-ui-sideline shows what I presume is unicode information for an icon (or character) that is missing. I try to show this in the attached screenshot.

![emacs-lsp-ui-strange-icon](https://user-images.githubusercontent.com/8569604/35666270-a9576e80-0729-11e8-88ae-9a7f8c45bb4e.png)

The first "character" of the line in yellow on the right side is a small square with unicode information instead of a proper character or icon. Am I missing something in my installation or can it perhaps be a setting somewhere that needs tweeking?

**Comment by sebastiencs** [comment]
@clearmisp  This is because of the variable `lsp-ui-sideline-code-actions-prefix` which contains a glyph your font doesn't have.
This should be display like that:
![capture du 2018-02-04 07-13-49](https://user-images.githubusercontent.com/5273820/35774815-4e55f796-097b-11e8-9620-634e61f07c8d.png)

I was wondering how long it took before someone complains about that. I will change the default ;)

**Comment by clearmisp** [comment]
@sebastiencs A natural question then arrises; what font do you use that contains this glyph? :-)

**Comment by sebastiencs** [comment]
I'm using [Hack](https://sourcefoundry.org/hack/). I think most of recent fonts should include that glyph.
The real question is what font are you using which doesn't have it :)
